apiVersion: v2
name: redis
description: Redis wrapper for GameKube
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: 28.2.2
    repository: https://charts.bitnami.com/bitnami
