services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: gamekube-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/data/import:/opt/keycloak/data/import:ro
