services:
  postgres:
    image: postgres:18-alpine
    container_name: gamekube-postgres
    environment:
      POSTGRES_DB: gamekube
      POSTGRES_USER: gamekube
      POSTGRES_PASSWORD: gamekube
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    container_name: gamekube-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/data/import:/opt/keycloak/data/import:ro
      - ./infra/keycloak/themes/keywind/theme:/opt/keycloak/themes:ro
