global:
  security:
    allowInsecureImages: true

keycloak:
  image:
    registry: ghcr.io
    repository: nayetdet/gamekube
    tag: keycloak
    pullPolicy: Always
  args:
    - start-dev
    - --import-realm
  extraEnvVars:
    - name: KC_DB
      value: postgres
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_DB_KIND_APPLICATION
      value: postgres
    - name: KC_DB_URL_FULL_APPLICATION
      value: jdbc:postgresql://gamekube-postgresql:5432/gamekube?currentSchema=gamekube
    - name: KC_DB_USERNAME_APPLICATION
      value: gamekube
    - name: KC_DB_PASSWORD_APPLICATION
      valueFrom:
        secretKeyRef:
          name: gamekube-postgresql
          key: password
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: keycloak.gamekube.localhost
    servicePort: http
    tls: false
    extraTls:
      - hosts:
          - keycloak.gamekube.localhost
        secretName: gamekube-tls
  proxyHeaders: xforwarded
  hostnameStrict: true
  usePasswordFiles: false
  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 60
  defaultInitContainers:
    prepareWriteDirs:
      enabled: false
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: true
    nameOverride: keycloak-postgresql
    fullnameOverride: gamekube-keycloak-postgresql
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: latest
      pullPolicy: Always
    auth:
      username: keycloak
      password: keycloak
      database: keycloak
