server:
  port: 8000
  forward-headers-strategy: framework
spring:
  application:
    name: gamekube
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    default-schema: gamekube
    schemas: gamekube
    validate-migration-naming: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
game:
  namespace: gamekube
  domain: gamekube.localhost
  tls-secret: gamekube-tls
  protocol: https
  readiness-timeout: 120s
