server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: gamekube
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:7000/realms/gamekube}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

game:
  namespace: gamekube
  domain: gamekube.localhost
  tls-secret: gamekube-tls
  protocol: https
  readiness-timeout-seconds: 120
