traefik:
  deployment:
    kind: DaemonSet
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  ingressClass:
    enabled: true
    isDefaultClass: true
    name: traefik
  providers:
    kubernetesIngress:
      enabled: true
      ingressClass: traefik
  ports:
    web:
      port: 8000
      hostPort: 80
      exposedPort: 80
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    websecure:
      port: 8443
      hostPort: 443
      exposedPort: 443
  service:
    spec:
      type: ClusterIP
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
