apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamekube
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cavestory
                port:
                  name: http
