apiVersion: v2
name: postgres
description: PostgreSQL wrapper for GameKube
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    version: 18.11.6
    repository: https://charts.bitnami.com/bitnami
